[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "bluemangoscorekeeper"
version = "0.2.2"
description = "A simple Python scorekeeper for different games"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"

[project.scripts]
scorekeeper = "scorer:main"

[tool.setuptools]
py-modules = ["scorer"]
