[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bluemangoscorekeeper"
version = "0.1.0"
description = "A simple Python scorekeeper for different games"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

[project.scripts]
scorekeeper = "bluemangoscorekeeper.scorer:main"

[tool.setuptools.packages.find]
where = ["src"]
